# Exercise 1
# Rachel Rolle

In [1]:
import numpy as np

### 1 & 2

In [5]:
#1
A= np.random.rand(6,6)
#2
A


array([[0.87972945, 0.96107855, 0.44518859, 0.86942743, 0.17306257,
        0.62901395],
       [0.40654031, 0.01289677, 0.31209995, 0.0361259 , 0.63009337,
        0.72483631],
       [0.11219117, 0.25001147, 0.08346973, 0.41791816, 0.47780083,
        0.23522676],
       [0.35686046, 0.84388486, 0.66197145, 0.97543985, 0.33499936,
        0.38487355],
       [0.26555203, 0.5583807 , 0.03344864, 0.56889254, 0.36433811,
        0.76528793],
       [0.20224049, 0.67176685, 0.75753034, 0.84311203, 0.10631295,
        0.12665512]])

### 3

In [8]:
#3 
m,n = A.shape
A
for i in range(1,n,2):
    print(A[:,i])

[0.96107855 0.01289677 0.25001147 0.84388486 0.5583807  0.67176685]
[0.86942743 0.0361259  0.41791816 0.97543985 0.56889254 0.84311203]
[0.62901395 0.72483631 0.23522676 0.38487355 0.76528793 0.12665512]


### 4

In [11]:
#4
myDict = {'odd':0, 'even':0}
for i in range(m):
    for j in range(n):
        if (i+j)%2 == 0:
            myDict['even'] += A[i,j]
        else:
            myDict['odd'] += A[i,j]

myDict

{'odd': 9.023886185114257, 'even': 7.454372339754454}

### 5

In [27]:
#5
class matrixMaker:
    def __init__(self, m, n):
        self.rows = m
        self.cols = n
        self.A = np.random.rand(m,n)

    def specialSum(self):
        sum = 0
        for i in range(self.rows):
            for j in range(self.cols):
                if self.A[i,j] > 0.5:
                    sum += self.A[i,j]
        return sum

In [28]:
test = matrixMaker(5,5)

In [29]:
test.A

array([[0.71398083, 0.48887614, 0.4511016 , 0.11668288, 0.12770904],
       [0.5667779 , 0.36709582, 0.98665086, 0.29923602, 0.14793669],
       [0.28011662, 0.23319767, 0.80551689, 0.64534221, 0.00990966],
       [0.67502313, 0.54741173, 0.24529861, 0.70073413, 0.38605405],
       [0.04539106, 0.46624765, 0.599022  , 0.28831907, 0.71772419]])

In [30]:
test.A[1,3]

0.2992360247848267

In [31]:
test.specialSum()

6.958183868501792

# Exercise 2

### 1

In [43]:

#1
import nltk

### 2

In [45]:
#2
from nltk.stem.porter import *
stemmer_p = PorterStemmer()

In [46]:
plurals = ['apples', 'bananas', 'cherries', 'oranges', 'grapes',
           'peaches', 'kiwis', 'strawberries', 'blueberries', 'watermelons',
           'lemons', 'limes', 'pineapples', 'blackberries', 'mangos',
           'apricots', 'pears', 'figs', 'pomegranates', 'cranberries']

In [47]:

singles_p = [stemmer_p.stem(plural) for plural in plurals]
print(singles_p)

['appl', 'banana', 'cherri', 'orang', 'grape', 'peach', 'kiwi', 'strawberri', 'blueberri', 'watermelon', 'lemon', 'lime', 'pineappl', 'blackberri', 'mango', 'apricot', 'pear', 'fig', 'pomegran', 'cranberri']


### Pracitce

In [48]:
#Practice
from nltk.stem.snowball import SnowballStemmer
stemmer_s = SnowballStemmer('english')
singles_s = [stemmer_s.stem(plural) for plural in plurals]
print(singles_s)

### 3

In [50]:
#3
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

import nltk
#nltk.download('wordnet')

lemm_p = [lemmatizer.lemmatize(plural) for plural in plurals]
print(lemm_p)

lemm_s = [lemmatizer.lemmatize(plural) for plural in plurals]
print(lemm_s)

In [58]:
#nltk.download('punkt')
from nltk.tokenize import word_tokenize

text = "Wow, we can finally stop using the split function!"
print(word_tokenize(text))

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\rchlr\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


['Wow', ',', 'we', 'can', 'finally', 'stop', 'using', 'the', 'split', 'function', '!']


# Exercise 3

### 1

In [10]:
#1

with open('nemo.txt', 'r') as nemo:
    content = nemo.read()



### 2 How many words total were there in this script?

In [18]:
#2 How many words total were there in this script?
words = content.split(' ')

tot_words = len(words)
print(tot_words)

11863


### 3 How many times did a character speak in this movie? Who spoke the most?

In [25]:
from collections import Counter

#Tracking each line
lines = content.split('\n')

#Distinguishing which line is a character's (by uppercase word)
characters = [line.strip() for line in lines if line and line[-1].isupper()]

# Count the occurrences of each character
character_counts = Counter(characters)

#Counting characters and lines
counted_lines = []
for character, count in character_counts.items():
    counted_line = f'{character}: {count} times'
    counted_lines.append(counted_line)

#Which character spoke the most?
for line in counted_lines:
    print(line)

print('Marlin spoke the most: 368 times')

MARLIN: 368 times
CORAL: 17 times
NEMO: 156 times
FISH KIDS: 1 times
FISH MOM: 1 times
CRAB KID: 1 times
BOB: 10 times
TED: 4 times
BILL: 4 times
BOB/TED: 1 times
KIDS: 4 times
MR. JOHANSSEN: 1 times
PEARL: 6 times
TAD: 9 times
SHELDON: 5 times
MR. RAY: 22 times
JIMMY: 1 times
FISH KID: 1 times
DIVER: 1 times
DORY: 252 times
BRUCE: 38 times
ANCHOR: 15 times
CHUM: 18 times
BRUCE/ANCHOR/CHUM: 3 times
ANCHOR/CHUM: 2 times
MARLIN/DORY: 7 times
PELICAN: 6 times
DENTIST: 29 times
BARBARA: 5 times
PATIENT: 4 times
BUBBLES: 14 times
PEACH: 40 times
JACQUES: 12 times
BLOAT: 43 times
DEB: 24 times
GURGLE: 39 times
NIGEL: 35 times
GILL: 90 times
BOTH: 1 times
BLOAT/BUBBLES/GURGLE: 5 times
GILL/NEMO: 1 times
MOONFISH LEADER: 16 times
MOONFISH TED: 1 times
can't miss it, it's in..that direction. And then you gotta follow that for about, I: 1 times
MOONFISH SCHOOL: 1 times
CRUSH: 29 times
SQUIRT: 12 times
CRUSH/SQUIRT: 1 times
TURTLE KIDS: 4 times
TURTLE KID: 1 times
SMALL FISH: 2 times
BIG FISH: 1 